name: hwe
channels:
  - defaults
  - conda-forge
  - pytorch
  - pip
dependencies:
  - python=3.8.0
  - mkl < 2022
  - pandas
  - numpy
  - tqdm
  - pytorch
  - jupyterlab
  - yfinance
  - matplotlib
  - openpyxl
  - ipywidgets
  - cvxopt
  - statsmodels
  # - tick
